version: '3.7'
services:
  netstats:
    hostname: netstats
    ports:
      - 3000:3000
    build:
      context: netstats
    container_name: netstats
    environment:
      WS_SECRET: ${NETSTATS_SECRET}
    networks:
      - research
  bootnode:
    container_name: bootnode
    build:
      context: node
    ports:
      - 30301:30301/udp
    command: bootnode --nodekeyhex ${BOOTNODE_KEY}
    networks:
      research:
        ipv4_address: 172.3.0.111
  node-1:
    depends_on:
      - bootnode
    build:
      context: node
    container_name: node-1
    ports:
      - 8545:8545
    command: geth
      --syncmode full
      --bootnodes enode://${BOOTNODE_ID}@172.3.0.111:30301
      --networkid ${NETWORK_ID}
      --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "personal,eth,web3,net,admin,db"
      --ws --wsaddr="0.0.0.0" --wsorigins="*" --wsapi="personal,eth,net,web3"
      --miner.gasprice 0
      --unlock "${ACCOUNT_0}" --password password.txt
      --ethstats node-1:${NETSTATS_SECRET}@netstats:3000
    networks:
      - research
  node-2:
    depends_on:
      - bootnode
    build:
      context: node
    container_name: node-2
    ports:
      - 8546:8545
    command: geth
      --syncmode full
      --bootnodes enode://${BOOTNODE_ID}@172.3.0.111:30301
      --networkid ${NETWORK_ID}
      --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "personal,eth,web3,net,admin,db"
      --ws --wsaddr="0.0.0.0" --wsorigins="*" --wsapi="personal,eth,net,web3"
      --miner.gasprice 0
      --ethstats node-2:${NETSTATS_SECRET}@netstats:3000
    networks:
      - research
  node-miner-1:
    depends_on:
      - bootnode
      - netstats
    build:
      context: node
    container_name: node-miner-1
    ports:
      - 8547:8545
    command: geth
      --syncmode full
      --bootnodes enode://${BOOTNODE_ID}@172.3.0.111:30301
      --networkid ${NETWORK_ID}
      --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,web3,net,admin,db,miner"
      --mine --miner.etherbase ${ACCOUNT_1} --miner.gasprice 0
      --unlock ${ACCOUNT_1} --password password.txt
      --ethstats node-miner-1:${NETSTATS_SECRET}@netstats:3000
    networks:
      - research
  node-miner-2:
    depends_on:
      - bootnode
      - netstats
    build:
      context: node
    container_name: node-miner-2
    ports:
      - 8548:8545
    command: geth
      --syncmode full
      --bootnodes enode://${BOOTNODE_ID}@172.3.0.111:30301
      --networkid ${NETWORK_ID}
      --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,web3,net,admin,db,miner"
      --mine --miner.etherbase ${ACCOUNT_2} --miner.gasprice 0
      --unlock ${ACCOUNT_2} --password password.txt
      --ethstats node-miner-2:${NETSTATS_SECRET}@netstats:3000
    networks:
      - research
  node-miner-3:
    depends_on:
      - bootnode
      - netstats
    build:
      context: node
    container_name: node-miner-3
    ports:
      - 8549:8545
    command: geth
      --syncmode full
      --bootnodes enode://${BOOTNODE_ID}@172.3.0.111:30301
      --networkid ${NETWORK_ID}
      --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,web3,net,admin,db,miner"
      --mine --miner.etherbase ${ACCOUNT_3} --miner.gasprice 0
      --unlock ${ACCOUNT_3} --password password.txt
      --ethstats node-miner-3:${NETSTATS_SECRET}@netstats:3000
    networks:
      - research

networks:
  research:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/24